# Generated by Django 3.0.7 on 2020-07-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='folder',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
