# Generated by Django 3.0.7 on 2020-07-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_alllogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='cedge_Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(default='', max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
