# Generated by Django 3.0.7 on 2020-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
