# Generated by Django 3.0.7 on 2020-08-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_auto_20200804_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
