# Generated by Django 3.0.7 on 2020-08-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(default='', related_name='tag_question_master', to='test1.Tags'),
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='tags',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='tags',
            field=models.ManyToManyField(default='', related_name='tag_tutorial_master', to='test1.Tags'),
        ),
    ]
