# Generated by Django 3.0.7 on 2020-08-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_auto_20200808_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(related_name='tag_question_master', to='test1.Tags'),
        ),
    ]
