# Generated by Django 3.0.7 on 2020-11-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_auto_20200808_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ML_id', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
