# Generated by Django 3.0.7 on 2020-11-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test1', '0014_mldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastOpenedQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_1', models.IntegerField(default=0)),
                ('index_2', models.IntegerField(default=0)),
                ('index_3', models.IntegerField(default=0)),
                ('index_4', models.IntegerField(default=0)),
                ('index_5', models.IntegerField(default=0)),
                ('index_6', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_opened', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
